package wiz8.recovery;

/** The compiler/linker emission represented by one Ghidra function. */
public enum EmissionKind {
	AUTHORED_BODY,
	CONSTRUCTOR_BODY,
	BASE_CONSTRUCTOR,
	COMPLETE_CONSTRUCTOR,
	VBASE_CONSTRUCTOR,
	BASE_DESTRUCTOR,
	COMPLETE_DESTRUCTOR,
	SCALAR_DELETING_DESTRUCTOR,
	VECTOR_DELETING_DESTRUCTOR,
	VBASE_DESTRUCTOR,
	ADJUSTOR_THUNK,
	COVARIANT_RETURN_THUNK,
	IMPORT_THUNK,
	DEFAULT_CONSTRUCTOR_CLOSURE,
	VECTOR_CONSTRUCTOR_ITERATOR,
	VECTOR_DESTRUCTOR_ITERATOR,
	ARRAY_UNWIND,
	LOCAL_STATIC_GUARD,
	TEMPLATE_EMISSION,
	LIBRARY_BODY
}
