package wiz8.exporter;

/** The compiler/linker emission represented by one Ghidra function. */
public enum EmissionKind {
	AUTHORED_BODY,
	CONSTRUCTOR_BODY,
	BASE_DESTRUCTOR,
	COMPLETE_DESTRUCTOR,
	SCALAR_DELETING_DESTRUCTOR,
	VECTOR_DELETING_DESTRUCTOR,
	VBASE_DESTRUCTOR,
	ADJUSTOR_THUNK,
	COVARIANT_RETURN_THUNK,
	IMPORT_THUNK,
	DEFAULT_CONSTRUCTOR_CLOSURE,
	VECTOR_CONSTRUCTOR_ITERATOR,
	VECTOR_DESTRUCTOR_ITERATOR,
	ARRAY_UNWIND,
	EH_FUNCLET,
	DYNAMIC_INITIALIZER,
	DYNAMIC_FINALIZER,
	LOCAL_STATIC_GUARD,
	TEMPLATE_EMISSION,
	INLINE_COMDAT,
	LIBRARY_BODY
}
