#ifndef WIZ8_SGP_COMPAT_WIZ_LIBS_H
#define WIZ8_SGP_COMPAT_WIZ_LIBS_H

#define NUMBER_OF_LIBRARIES 6
#define MAX_NUMBER_OF_LIBRARIES 56

extern LibraryInitHeader gGameLibaries[MAX_NUMBER_OF_LIBRARIES];

#endif
