#pragma once

/* The retail table at 0x0060ea08 supplies these 27 script cycle names in
   index order. Monster cycles differ from physical attack-mode indices and
   from spell-visual cycle groups. GrCycle's shared byte-sized ABI stays intact. */
enum W8MonsterCycle {
    W8_MONSTER_CYCLE_BIRTH = 0,
    W8_MONSTER_CYCLE_IDLE = 1,
    W8_MONSTER_CYCLE_SPICE = 2,
    W8_MONSTER_CYCLE_TRANSITION = 3,
    W8_MONSTER_CYCLE_WALK = 4,
    W8_MONSTER_CYCLE_DRAW = 5,
    W8_MONSTER_CYCLE_ATTACK_CLOSE = 6,
    W8_MONSTER_CYCLE_ATTACK_RANGED = 7,
    W8_MONSTER_CYCLE_UNUSED = 8,
    W8_MONSTER_CYCLE_ATTACK_SWING = 9,
    W8_MONSTER_CYCLE_ATTACK_THRUST = 10,
    W8_MONSTER_CYCLE_ATTACK_BASH = 11,
    W8_MONSTER_CYCLE_ATTACK_MELEE = 12,
    W8_MONSTER_CYCLE_ATTACK_THROW = 13,
    W8_MONSTER_CYCLE_ATTACK_PUNCH = 14,
    W8_MONSTER_CYCLE_ATTACK_KICK = 15,
    W8_MONSTER_CYCLE_ATTACK_LASH = 16,
    W8_MONSTER_CYCLE_ATTACK_SHOOT = 17,
    W8_MONSTER_CYCLE_ATTACK_SPECIAL = 18,
    W8_MONSTER_CYCLE_DODGE = 19,
    W8_MONSTER_CYCLE_GET_HIT = 20,
    W8_MONSTER_CYCLE_DIE = 21,
    W8_MONSTER_CYCLE_TURN = 22,
    W8_MONSTER_CYCLE_TALK_SPICE = 23,
    W8_MONSTER_CYCLE_TALK = 24,
    W8_MONSTER_CYCLE_SPELL = 25,
    W8_MONSTER_CYCLE_SPECIAL = 26,
    W8_MONSTER_CYCLE_NONE = -1,
    W8_MONSTER_CYCLE_COUNT = 27
};

/* Selector for the mixed integer animation-query interface. */
enum W8MonsterQueryKind {
    W8_MONSTER_QUERY_FRAME_COUNT = 0,
    W8_MONSTER_QUERY_ANIMATION_COUNT = 1,
    W8_MONSTER_QUERY_AT_PLAYBACK_END = 2,
    W8_MONSTER_QUERY_AT_PLAYBACK_START = 3,
    W8_MONSTER_QUERY_FRAME = 4,
    W8_MONSTER_QUERY_HAS_FRAMES = 5,
    W8_MONSTER_QUERY_CYCLE = 6,
    W8_MONSTER_QUERY_CYCLE_COMPLETE = 7,
    W8_MONSTER_QUERY_SUBCYCLE = 9
};
